//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dia_Supermarket.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_dia_supermarketEntities : DbContext
    {
        public db_dia_supermarketEntities()
            : base("name=db_dia_supermarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Admins> tb_Admins { get; set; }
        public virtual DbSet<tb_Categories> tb_Categories { get; set; }
        public virtual DbSet<tb_Orders> tb_Orders { get; set; }
        public virtual DbSet<tb_Orders_Summary> tb_Orders_Summary { get; set; }
        public virtual DbSet<tb_Products> tb_Products { get; set; }
        public virtual DbSet<tb_Products_Rating> tb_Products_Rating { get; set; }
        public virtual DbSet<tb_Users> tb_Users { get; set; }
        public virtual DbSet<tb_Wishlist> tb_Wishlist { get; set; }
    }
}
