//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dia_Supermarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Orders_Summary
    {
        public int order_detail_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual tb_Orders tb_Orders { get; set; }
        public virtual tb_Products tb_Products { get; set; }
    }
}
