//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dia_Supermarket.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Products()
        {
            this.tb_Orders_Summary = new HashSet<tb_Orders_Summary>();
            this.tb_Products_Rating = new HashSet<tb_Products_Rating>();
            this.tb_Wishlist = new HashSet<tb_Wishlist>();
        }
    
        public int product_id { get; set; }


        [Required(ErrorMessage = "Please enter product name.")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "Product name cannot be longer than 100 characters")]
        public string product_name { get; set; }


        [Required(ErrorMessage = "Please enter SKU.")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "SKU cannot be longer than 100 characters")]
        public string sku { get; set; }


        //[Required(ErrorMessage = "Please select product image.")]
        public string product_image { get; set; }


        [StringLength(250, MinimumLength = 1, ErrorMessage = "Description cannot be longer than 250 characters")]
        public string long_description { get; set; }


        [Required(ErrorMessage = "Please enter price.")]
        [Range(0.00, 99999.99, ErrorMessage = "Price can not be greater than 99999")]
        public Nullable<decimal> price { get; set; }


        [Required(ErrorMessage = "Please enter stock.")]
        [Range(0, 99999, ErrorMessage = "Stock can not be greater than 99999")]
        public Nullable<int> stock { get; set; }


        [Required(ErrorMessage = "Please select category name.")]
        public Nullable<int> category_id { get; set; }


        public Nullable<System.DateTime> inserted_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> updated_by_admin { get; set; }
    
        public virtual tb_Admins tb_Admins { get; set; }
        public virtual tb_Categories tb_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Orders_Summary> tb_Orders_Summary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Products_Rating> tb_Products_Rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Wishlist> tb_Wishlist { get; set; }
    }
}
