//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dia_Supermarket.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Users()
        {
            this.tb_Orders = new HashSet<tb_Orders>();
            this.tb_Products_Rating = new HashSet<tb_Products_Rating>();
            this.tb_Wishlist = new HashSet<tb_Wishlist>();
        }
    
        public int user_id { get; set; }


        [Required(ErrorMessage = "Please enter first name.")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "First name cannot be longer than 100 characters")]
        public string first_name { get; set; }


        [StringLength(100, MinimumLength = 1, ErrorMessage = "Last name cannot be longer than 100 characters")]
        public string last_name { get; set; }


        [Required(ErrorMessage = "Please enter contact number.")]
        [StringLength(15, MinimumLength = 1, ErrorMessage = "Contact number cannot be longer than 15 characters")]
        [RegularExpression(@"[0][3][0-9]{2}[\-]?[0-9]{7}", ErrorMessage = "Correct format is: 0333(-)3333333.")]
        public string contact_num { get; set; }


        [Required(ErrorMessage = "Please enter email address.")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Email address must be at least 5 characters long and cannot be longer than 50 characters")]
        public string email_address { get; set; }


        [Required(ErrorMessage = "Please enter password.")]
        [StringLength(20, MinimumLength = 1, ErrorMessage = "password cannot be longer than 20 characters")]
        public string user_password { get; set; }


        [Required(ErrorMessage = "Please re-enter password")]
        [Compare("user_password", ErrorMessage = "Password does not match")]
        public string confirm_password { get; set; }


        [Required(ErrorMessage = "Please enter your address.")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "Address cannot be longer than 50 characters")]
        public string user_address { get; set; }


        [Required(ErrorMessage = "Please enter city.")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "City name cannot be longer than 50 characters")]
        public string city { get; set; }


        [Required(ErrorMessage = "Please enter country.")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "Country cannot be longer than 50 characters")]
        public string country { get; set; }


        [Required(ErrorMessage = "Please enter postal code.")]
        [Range(1000, 99999, ErrorMessage = "Postal Code can only be 4 or 5 digits long")]
        public Nullable<int> postal_code { get; set; }


        [Required(ErrorMessage = "Please select gender.")]
        public string gender { get; set; }


        public Nullable<System.DateTime> join_date { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> updated_by_admin { get; set; }
    
        public virtual tb_Admins tb_Admins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Orders> tb_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Products_Rating> tb_Products_Rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Wishlist> tb_Wishlist { get; set; }
    }
}
